# Generated by Django 4.2.13 on 2024-05-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_category_options_alter_news_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
