# Generated by Django 4.2.13 on 2024-05-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='price',
        ),
        migrations.RemoveField(
            model_name='news',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
